import type { Metadata } from "next";
import { ProductProvider } from "../context/product/ProductContext";
import { CartProvider } from "@/context/cart/CartContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sneakerfit",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

function RootLayout({ children }: Readonly<Props>) {
  return (
    <ProductProvider>
      <CartProvider>
        <html lang="en" className="antialiased">
          <body className="min-h-screen font-dm-sans bg-background text-text-primary">
            {children}
          </body>
        </html>
      </CartProvider>
    </ProductProvider>
  );
}
export default RootLayout;
